### ISSUE TITLE
Build error on macOS

### ISSUE THREAD

**Issue by sgammon** [material-components/material-web#2337]
**Describe the bug**
When trying to build a fresh copy of MWC on mac (according to the README), I get the error enclosed.

**To Reproduce**
1. Use a Mac
2. `git clone git@github.com:material-components/material-components-web-components.git mwc`
3. `cd mwc && npm install && npm run build`
4. See error:

```
Generating packages/circular-progress/mwc-circular-progress-css.ts
Error: 1568.2352941176deg*ms/deg isn't a valid CSS value.
    ╷
239 │         animation: mdc-circular-progress-container-rotate $duration linear
    │ ┌──────────────────^
240 │ │         infinite;
    │ └────────────────^
    ╵
  node_modules/@material/circular-progress/_mixins.scss 239:18  root stylesheet
    at Object._newRenderError (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:13628:19)
    at Object._wrapException (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:13474:16)
    at _render_closure1.call$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:77359:21)
    at _RootZone.runBinary$3$3 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:25587:18)
    at _RootZone.runBinary$3 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:25591:19)
    at _FutureListener.handleError$1 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:24041:19)
    at _Future__propagateToListeners_handleError.call$0 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:24337:40)
    at Object._Future__propagateToListeners (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:3497:88)
    at _Future._completeError$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:24165:9)
    at _AsyncAwaitCompleter.completeError$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:23557:12) {
  formatted: "Error: 1568.2352941176deg*ms/deg isn't a valid CSS value.\n" +
    '    ╷\n' +
    '239 │         animation: mdc-circular-progress-container-rotate $duration linear\n' +
    '    │ ┌──────────────────^\n' +
    '240 │ │         infinite;\n' +
    '    │ └────────────────^\n' +
    '    ╵\n' +
    '  node_modules/@material/circular-progress/_mixins.scss 239:18  root stylesheet',
  line: 239,
  column: 18,
  file: '/Volumes/VANTAGE/material-components-web-components/node_modules/@material/circular-progress/_mixins.scss',
  status: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! material-components-web-components@ build:styling: `./scripts/build-styling.sh`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the material-components-web-components@ build:styling script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Expected behavior**
I expect the build to succeed for a tagged release

**Screenshots**
Not applicable

**Browser Version (please complete the following information):**
 - OS: macOS Big Sur - `11.2.3`
 - Browser: Not applicable
 - Version: Not applicable
- Node Version: `v12.20.1`

**Additional context**

**Comment by e111077** [comment]
Heya, thanks for the detailed bug report! Unfortunately I'm unable to reproduce the issue.

Though, a possible solution may be to re-sync our repo with the upstream mdc repo in which those failing styles live.

After #2338 merges, can you please try removing your node_modules directory, reinstalling, and rebuilding and letting me know if that solves this issue?

**Comment by sgammon** [comment]
@e111077 thank you for getting back to me so quickly 😄 

i see that the referenced PR has been merged. so, locally, i jumped into `mwc`, and did:
`git checkout master && git pull origin master`

then

`npx lerna clean && git pull && rm -rf node_modules && npm i && npm run build`

as suggested. I still get the error mentioned:
```
...
Generating packages/circular-progress/mwc-circular-progress-css.ts
Error: 1568.2352941176deg*ms/deg isn't a valid CSS value.
...
```

**Comment by e111077** [comment]
Hmm let's dig into the setup.

Which version of node are you on?
Can you `npm ls sass` and let me know what version is installed?
Also run `npm ls node-sass-import`

This is a bit of a puzzle for sure 😅  Sass can math away units and those units in the error should def simplify to `ms` and we're not doing any stringification in the code...

**Comment by sgammon** [comment]
**`npm ls sass`**:
```
➜  material-components-web-components git:(master) ✗ npm ls sass                                    
material-components-web-components@ /Volumes/VANTAGE/material-components-web-components
└── sass@1.32.5 
```

**`npm ls node-sass-import`**:
```
➜  material-components-web-components git:(master) ✗ npm ls node-sass-import
material-components-web-components@ /Volumes/VANTAGE/material-components-web-components
└── node-sass-import@2.0.1 
```

I don't have a `sass` binary installed globally. WDYT @e111077? is there a way i can work around this, perhaps by not using `mwc-circular-progress` for now?

**Comment by e111077** [comment]
I'm afraid it may just break further down the line but this is what you should do to exclude circular progress:

1. delete `circular-progress` from `rollup.config.js`
2. delete the directory for `circular-progress` and `circular-progress-four-color`
3. delete `packages/circular-progress` and `packages/circular-progress-four-color` from `tsconfig.json`

**Comment by dfreedm** [comment]
Are you still seeing this issue?

**Comment by sgammon** [comment]
@dfreedm yes :(

```
Generating packages/circular-progress/mwc-circular-progress-css.ts
Error: 1568.2352941176deg*ms/deg isn't a valid CSS value.
    ╷
240 │         animation: mdc-circular-progress-container-rotate $duration linear
    │ ┌──────────────────^
241 │ │         infinite;
    │ └────────────────^
    ╵
  node_modules/@material/circular-progress/_mixins.scss 240:18  root stylesheet
    at Object._newRenderError (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:13494:19)
    at Object._wrapException (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:13337:16)
    at _render_closure1.call$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:80007:21)
    at _RootZone.runBinary$3$3 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:27193:18)
    at _FutureListener.handleError$1 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:25721:19)
    at _Future__propagateToListeners_handleError.call$0 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:26018:49)
    at Object._Future__propagateToListeners (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:4539:77)
    at _Future._completeError$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:25851:9)
    at _AsyncAwaitCompleter.completeError$2 (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:25194:12)
    at Object._asyncRethrow (/Volumes/VANTAGE/material-components-web-components/node_modules/sass/sass.dart.js:4288:17) {
  formatted: "Error: 1568.2352941176deg*ms/deg isn't a valid CSS value.\n" +
    '    ╷\n' +
    '240 │         animation: mdc-circular-progress-container-rotate $duration linear\n' +
    '    │ ┌──────────────────^\n' +
    '241 │ │         infinite;\n' +
    '    │ └────────────────^\n' +
    '    ╵\n' +
    '  node_modules/@material/circular-progress/_mixins.scss 240:18  root stylesheet',
  line: 240,
  column: 18,
  file: '/Volumes/VANTAGE/material-components-web-components/node_modules/@material/circular-progress/_mixins.scss',
  status: 1
}
```

obviously, i pulled from master first. then, ran the `npx lerna clean ...` one-liner from earlier in the thread.

**Comment by sgammon** [comment]
i do see that
`line: 239`

changed to
`line: 240`

lol

**Comment by dfreedm** [comment]
Thanks. I'm having trouble replicating this, but maybe `git clean -fdx && npm ci` would help?

**Comment by asyncLiz** [comment]
Obsolete with new wireit setup
