### ISSUE TITLE
Can not use mwc-tab-bar with mwc-fab  - "mwc-ripple" has already been used with this registry

### ISSUE THREAD

**Issue by dman777** [material-components/material-web#3656]
When using mwc-tab-bar with mwc-fab, I get: 

> Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-ripple" has already been used with this registry
    at legacyCustomElement (http://xxx/node_modules/@lit/reactive-element/development/decorators/custom-element.js:7:27)
    at http://xxxx/node_modules/@lit/reactive-element/development/decorators/custom-element.js:42:7
    at __decorate (http://xxxx/node_modules/@material/mwc-ripple/node_modules/tslib/tslib.es6.js:58:95)
    at http://xxxx/node_modules/@material/mwc-ripple/mwc-ripple.js:16:10
    
    
 ```
    % npm list
cash-bro@1.0.2 /home/two/gitlab/cash-bro
├── @11ty/eleventy-plugin-syntaxhighlight@3.1.2
├── @11ty/eleventy@0.12.1
├── @custom-elements-manifest/analyzer@0.5.7
├── @esm-bundle/chai@4.3.4
├── @material/mwc-button@0.25.3
├── @material/mwc-fab@0.27.0
├── @material/mwc-icon@0.25.3
├── @material/mwc-tab-bar@0.25.3
├── @material/mwc-tab@0.25.3
├── @material/mwc-top-app-bar-fixed@0.25.3
├── @open-wc/testing-karma@4.0.9
├── @open-wc/testing@3.0.0-next.2
├── @rollup/plugin-node-resolve@13.0.4
├── @rollup/plugin-replace@3.0.0
├── @types/mocha@9.0.0
├── @web/dev-server-legacy@0.1.7
├── @web/dev-server-rollup@0.3.9
├── @web/dev-server@0.1.22
├── @web/test-runner-mocha@0.7.4
├── @web/test-runner-playwright@0.8.8
├── @web/test-runner@0.13.17
├── @webcomponents/webcomponentsjs@2.6.0
├── babel-eslint@10.1.0
├── deepmerge@4.2.2
├── eslint@7.32.0
├── lit-analyzer@1.2.1
├── lit@2.2.2
├── mocha@9.1.1
├── prettier@2.3.2
├── rimraf@3.0.2
├── rollup-plugin-summary@1.3.0
├── rollup-plugin-terser@7.0.2
└── rollup@2.56.3
```

I am importing as such:

```js
import {LitElement, html, css} from 'lit';
import '@material/mwc-fab';
import '@material/mwc-tab-bar';
import '@material/mwc-tab';


export class MainApp extends LitElement {
```

**Comment by dman777** [comment]
Closing as the versions of tab bar and fab are mismatched and need to match
