### ISSUE TITLE
`@ariaProperty` decorator is not SSR compatible

### ISSUE THREAD

**Issue by justinfagnani** [material-components/material-web#3736]
Rendering a MdOutlinedTextField in lit-ssr results in this error:

```
TypeError: Cannot convert undefined or null to object
    at MdOutlinedTextField.set (/Users/justinfagnani/Projects/WebComponents/webcomponents.org/webcomponents.org/node_modules/@material/web/decorators/aria-property.ts:53:29)
    at TextField (/Users/justinfagnani/Projects/WebComponents/webcomponents.org/webcomponents.org/node_modules/@material/web/textfield/lib/text-field.ts:108:28)
    at OutlinedTextField (/Users/justinfagnani/Projects/WebComponents/webcomponents.org/webcomponents.org/node_modules/@material/web/textfield/lib/outlined-text-field.ts:12:7)
    at MdOutlinedTextField (/Users/justinfagnani/Projects/WebComponents/webcomponents.org/webcomponents.org/node_modules/@material/web/textfield/outlined-text-field.ts:30:1)
    at LitElementRenderer (/Users/justinfagnani/Projects/WebComponents/webcomponents.org/webcomponents.org/node_modules/@lit-labs/ssr/src/lib/lit-element-renderer.ts:29:20)
```

It looks like here is accessing `this.dataset`:
https://github.com/material-components/material-web/blob/master/decorators/aria-property.ts#L53

Which is not something we have in our DOM shim. We need to decide if we can support that in lit-ssr.

**Comment by asyncLiz** [comment]
Removed decorator
