### ISSUE TITLE
Unable to set MatCalendar.activeDate with Luxon - Angular

### ISSUE THREAD

**Issue by torrezsae** [material-components/material-web#5693]
### What is affected?

Component

### Description

What I did : 
```
this.selectedDate = DateTime.fromISO(dateSring); // Luxon fromISO()
let date = this.selectedDate.toJSDate(); // Succesfully creates a proper date object

this.saveCalendar.activeDate = date; // Error occurs here
this.saveCalendar.updateTodaysDate()
```

Expected result : 
Active date is set and material calendar view is updated to the location of the current date.

Actual result:
An error occurs. 
```
Error: LuxonDateAdapter: Cannot format invalid date.
    at _LuxonDateAdapter.format (material-luxon-adapter.mjs:136:13)
    at get periodButtonDescription (datepicker.mjs:2612:32)
    at MatCalendarHeader_Template (datepicker.mjs:2742:36)
    at executeTemplate (core.mjs:11264:5)
    at refreshView (core.mjs:12817:7)
    at detectChangesInView (core.mjs:13025:5)
    at detectChangesInViewIfAttached (core.mjs:12987:3)
    at detectChangesInComponent (core.mjs:12976:3)
    at detectChangesInChildComponents (core.mjs:13037:5)
    at refreshView (core.mjs:12869:7)
```

Notes: 
I am using `provideLuxonDateAdapter()`. All other functionality works; I am able to select and format dates appropriately. Active date is being directly updated since [startAt] and [(ngModel)] binding does not automatically change the view of the calendar. When the MatCalendar.activeDate is not modified the correct date is selected according to the `selectedDate`.

### Reproduction

I currently do not have a working reproduction.

### Workaround

I have not found a workaround.

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Affected versions

@angular/material@18.1.0

### Browser/OS/Node environment

Google Chrome: 127.0.6533.100 (Official Build) (64-bit)
Angular CLI: 18.1.0
Node: 20.14.0
Package Manager: npm 10.7.0
OS: win32 x64

**Comment by torrezsae** [comment]
Forgot the most important versions:
```
@angular/material-luxon-adapter: 18.1.0
luxon: 3.5.0
```
